In [1]:
#Question 1 WIkipedia.org

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url='https://www.wikipedia.org/'

def wiki_webscraping(url):
    
    source=requests.get(url)
    soup=BeautifulSoup(source.text,'html.parser')
    soup

    header_language=[]
    link_language=[]

    i=1
    while i <=10:
        for j in  soup.find_all('div',class_='central-featured-lang lang'+str(i)):
            header_language.append(j.strong.text)
            link_language.append(j.a['href'].strip('/'))
        i+=1

    wiki_df=pd.DataFrame({'Header':header_language,'Header Link':link_language})
    return wiki_df
        
wiki_webscraping(url)

           Header       Header Link
0         English  en.wikipedia.org
1       æ¥æ¬èª  ja.wikipedia.org
2  Ð ÑÑÑÐºÐ¸Ð¹  ru.wikipedia.org
3         Deutsch  de.wikipedia.org
4        EspaÃ±ol  es.wikipedia.org
5       FranÃ§ais  fr.wikipedia.org
6        Italiano  it.wikipedia.org
7          ä¸­æ  zh.wikipedia.org
8      PortuguÃªs  pt.wikipedia.org
9          Polski  pl.wikipedia.org

In [2]:
# Question 2 IMDB top 100 movies

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url=['https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc','https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&start=51&ref_=adv_nxt']

def imdb_top(url):
    rank=[]
    name=[]
    year=[]
    rating=[]
    rep={'(':'',')':''}
    for i in range(len(url)):
        source= requests.get(url[i])
        soup=BeautifulSoup(source.text,'html.parser')

        for j in soup.find_all('h3',class_='lister-item-header') :
            rank.append(j.text.split('\n')[1].replace('.',''))
            name.append(j.text.split('\n')[2])
            year.append(j.find('span',class_='lister-item-year text-muted unbold').text)
        for i in soup.find_all('div', class_='inline-block ratings-imdb-rating') :
            rating.append(i.text.split('\n')[2])
        for key,value in rep.items():
            year = [ s.replace(key,value) for s in year]

        rank = [int(s) for s in rank]
        rating = [float(s) for s in rating]

    imdb_df= pd.DataFrame({'Ranking':rank,'Name of Film':name,'Year of Release':year ,'Rating of Film':rating })
    return imdb_df

imdb_top(url)

,Ranking,Name of Film,Year of Release,Rating of Film
0,1,The Shawshank Redemption,1994,9.3
1,2,The Godfather,1972,9.2
2,3,The Dark Knight,2008,9.0
3,4,The Lord of the Rings: The Return of the King,2003,9.0
4,5,Schindler's List,1993,9.0
...,...,...,...,...
95,96,North by Northwest,1959,8.3
96,97,Vertigo,1958,8.3
97,98,Singin' in the Rain,1952,8.3
98,99,Citizen Kane,1941,8.3
99,100,M,1931,8.3

In [3]:
# Question 3 IMDB top 100 Indian Movies

from bs4 import BeautifulSoup
import requests
import pandas as pd

url='https://www.imdb.com/india/top-rated-indian-movies/'

def imdb_indian_top(url):
    
    source=requests.get(url)
    source

    soup=BeautifulSoup(source.text,'html.parser')
    soup

    rank=[]
    name=[]
    year=[]
    rating=[]
    rep={'(':'',')':'','\n':''}

    movies = soup.find('tbody',class_='lister-list').find_all('tr')

    for i in movies:
        rank.append(i.find('td',class_='titleColumn').get_text(strip=True).split('.')[0])
        name.append(i.find('td',class_='titleColumn').a.text)
        year.append(i.find('td',class_='titleColumn').span.text.strip('()'))
        rating.append(i.find('td',class_='ratingColumn imdbRating').strong.text)

    # Formatting and slicing for 100 records
    rank = [int(s) for s in rank[0:100]]
    year = [int(s) for s in year[0:100]]
    rating = [float(s) for s in rating[0:100]]
    name = name[0:100]
    
    imdb_df=pd.DataFrame({'Ranking':rank,'Name of Movie':name,'Year of Release':year,'Rating of Movie':rating})
    return imdb_df

imdb_indian_top(url)

    Ranking                Name of Movie  Year of Release  Rating of Movie
0         1                     Jai Bhim             2021              8.4
1         2                   Anbe Sivam             2003              8.4
2         3                      Golmaal             1979              8.4
3         4                      Nayakan             1987              8.4
4         5            Pariyerum Perumal             2018              8.4
..      ...                          ...              ...              ...
95       96                       Masaan             2015              8.0
96       97  Baahubali 2: The Conclusion             2017              8.0
97       98                  قصّة منسيّة             2012              8.0
98       99                  رغبات القلب             2001              8.0
99      100                  777 Charlie             2022              8.0

[100 rows x 4 columns]

In [ ]:
# Question 4 former president of India
link for same is not opening and error 
"An error occurred while processing your request.
Reference #102.3b090ac3.1656508366.4f7f84" comes.
informed the same through Ticket to SME

In [4]:
# Program for Question 5a and 6a combined 5a(Top 10 Men ODI Teams)  6a(Top 10 Women ODI Teams) , please provide input

from bs4 import BeautifulSoup 
import requests
import pandas as pd
import numpy as np

mto='https://www.icc-cricket.com/rankings/mens/team-rankings/odi'
wto='https://www.icc-cricket.com/rankings/womens/team-rankings/odi'
mtt='https://www.icc-cricket.com/rankings/mens/team-rankings/test'


url_inp=input("Enter 'mto' for Men ODI ranking\n or \nEnter 'wto' for women ODI ranking : ")

url=[]

if url_inp=='mto':
    url.append(mto)
elif url_inp=='wto':
    url.append(wto)
elif url_inp=='mtt':
    url.append(mtt)


def icc_webscrap_team(url):
    for i in range(len(url)):
        source=requests.get(url[i])
        soup=BeautifulSoup(source.text,'html.parser')
        
        rank=[]
        name=[]
        matches=[]
        points=[]
        ratings=[]

        rank.append(soup.find('tr',class_='rankings-block__banner').text.split()[0])
        name.append(soup.find('span',class_='u-hide-phablet').text)
        matches.append(soup.find('tr',class_='rankings-block__banner').text.split()[-3])
        points.append(soup.find('tr',class_='rankings-block__banner').text.split()[-2])
        ratings.append(soup.find('tr',class_='rankings-block__banner').text.split()[-1])
        
        for i in soup.find_all('tr',class_='table-body'):
            rank.append(i.text.split()[0])
            name.append(i.find('span',class_='u-hide-phablet').text)
            matches.append(i.text.split()[-3])
            points.append(i.text.split()[-2])
            ratings.append(i.text.split()[-1])
            
    icc_team_df=pd.DataFrame({'Rankings':rank[0:10],'Name':name[0:10],'No of Matches':matches[0:10],'Total Points':points[0:10],'Rating':ratings[0:10]})
    return icc_team_df


icc_webscrap_team(url)

Enter 'mto' for Men ODI ranking
 or
Enter 'wto' for women ODI ranking : mto

  Rankings          Name No of Matches Total Points Rating
0        1   New Zealand            12        1,505    125
1        2       England            22        2,756    125
2        3      Pakistan            19        2,005    106
3        4         India            22        2,304    105
4        5     Australia            23        2,325    101
5        6  South Africa            19        1,872     99
6        7    Bangladesh            24        2,275     95
7        8     Sri Lanka            29        2,658     92
8        9   West Indies            32        2,306     72
9       10   Afghanistan            18        1,238     69

In [5]:
# Program for question 5b,5c and 6b,6c (5b-Top 10 men ODI batsmen,5c-Top 10 men ODI bowler , 6b-Top10 women ODI batting,6c-Top 10 Women allrounder) , please give input
from bs4 import BeautifulSoup 
import requests
import pandas as pd
import numpy as np

menbat='https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting'
menbow='https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling'
wombat='https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting'
womall='https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder'

url_inp=input("Enter any one among \n 'menbat' for Top10 Men Batsmen \n 'menbow' for Top10 Men Bowlers \n 'wombat' for Top10 Women batting \n 'womall' for Top10 women allrounders :  ")

url=[]

if url_inp=='menbat':
    url.append(menbat)
elif url_inp=='menbow':
    url.append(menbow)
elif url_inp=='wombat':
    url.append(wombat)
elif url_inp=='womall':
    url.append(womall)
    

def icc_webscrap_player(url):
    for i in range(len(url)):
        source=requests.get(url[i])
        soup=BeautifulSoup(source.text,'html.parser')

        rank=[]
        player_name=[]
        team=[]
        ratings=[]

        rank.append(soup.find('tr',class_='rankings-block__banner').text.split()[0])
        player_name.append(soup.find('div',class_='rankings-block__banner--name-large').text)
        team.append(soup.find('div',class_='rankings-block__banner--nationality').text.strip('\n'))
        ratings.append(soup.find('td',class_='u-text-left').text.strip('\n')) 

        for i in soup.find_all('tr',class_='table-body'):
            rank.append(i.text.split()[0])
            player_name.append(i.find('td',class_='table-body__cell rankings-table__name name').text.strip('\n'))
            team.append(i.find('span',class_='table-body__logo-text').text)
            ratings.append(i.find('td',class_='table-body__cell rating').text)

        rank=[int(s) for s in rank]
        ratings=[int(s) for s in ratings]

    icc_player_df=pd.DataFrame({'Rank of Player':rank[0:10],'Name of Player':player_name[0:10],'Team':team[0:10],'Total Rating':ratings[0:10]})
    return icc_player_df
    
icc_webscrap_player(url)

Enter any one among
 'menbat' for Top10 Men Batsmen
 'menbow' for Top10 Men Bowlers
 'wombat' for Top10 Women batting
 'womall' for Top10 women allrounders :  womall

   Rank of Player    Name of Player Team  Total Rating
0               1    Natalie Sciver  ENG           393
1               2      Ellyse Perry  AUS           374
2               3   Hayley Matthews   WI           338
3               4    Marizanne Kapp   SA           338
4               5       Amelia Kerr   NZ           335
5               6  Ashleigh Gardner  AUS           269
6               7     Deepti Sharma  IND           249
7               8     Jess Jonassen  AUS           245
8               9         Sune Luus   SA           223
9              10   Katherine Brunt  ENG           221

In [6]:
#Question 7 News headlines from CNBC
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url='https://www.cnbc.com/world/?region=world'

def cnbc_webscraping(url):
    source=requests.get(url)
    soup=BeautifulSoup(source.text,'html.parser')

    data=soup.find('div',class_='undefined LatestNews-isHomePage LatestNews-isIntlHomepage')
    
    headline=[]
    time=[]
    link=[]

    for i in data.find_all('div',class_='LatestNews-headlineWrapper'):
        headline.append(i.find('a',class_='LatestNews-headline').text)
        time.append(i.span.text)
        link.append(i.find('a',class_='LatestNews-headline')['href'])

    cnbc_df=pd.DataFrame({'Headline of news':headline,'Time since news released':time,'News Link':link})
    return cnbc_df

cnbc_webscraping(url)

,Headline of news,Time since news released,News Link
0,Google says it will delete location history fo...,8 Hours Ago,https://www.cnbc.com/2022/07/01/google-will-de...
1,Biden opens the possibility of more offshore o...,9 Hours Ago,https://www.cnbc.com/2022/07/01/biden-interior...
2,The last remnant of Facebook's crypto project ...,9 Hours Ago,https://www.cnbc.com/2022/07/01/the-last-remna...
3,Best trades on CNBC Friday: Where to buy these...,10 Hours Ago,https://www.cnbc.com/2022/07/01/best-trades-on...
4,What to watch in the markets in the week ahead,11 Hours Ago,https://www.cnbc.com/2022/07/01/recession-fear...
5,Trump media company subpoenaed in federal crim...,11 Hours Ago,https://www.cnbc.com/2022/07/01/trump-media-co...
6,What Micron's earnings beat but light guidance...,11 Hours Ago,https://www.cnbc.com/2022/07/01/investing-club...
7,"Investing Club: The week in review, the week a...",11 Hours Ago,https://www.cnbc.com/2022/07/01/investing-club...
8,FTX signs a deal giving it the option to buy c...,11 Hours Ago,https://www.cnbc.com/2022/07/01/ftx-signs-a-de...
9,Walmart working on response to Supreme Court a...,11 Hours Ago,https://www.cnbc.com/2022/07/01/walmart-workin...
10,Crypto broker Voyager Digital suspends trading...,12 Hours Ago,https://www.cnbc.com/2022/07/01/voyager-digita...
11,Self-driving cars from GM's Cruise block San F...,12 Hours Ago,https://www.cnbc.com/2022/07/01/self-driving-c...
12,Investment banks trumpet fresh ideas in new se...,12 Hours Ago,https://www.cnbc.com/2022/07/01/investment-ban...
13,Social Security Administration addressing mail...,13 Hours Ago,https://www.cnbc.com/2022/07/01/social-securit...
14,TikTok tells U.S. lawmakers it's working to pr...,13 Hours Ago,https://www.cnbc.com/2022/07/01/tiktok-says-it...
15,Russian and Chinese designs dominate nuclear r...,13 Hours Ago,https://www.cnbc.com/2022/07/01/russian-and-ch...
16,Chevron among Wall Street’s favorite dividend ...,13 Hours Ago,https://www.cnbc.com/2022/07/01/broadcom-chevr...
17,Activist investor group asks SEC to investigat...,14 Hours Ago,https://www.cnbc.com/2022/07/01/activist-inves...
18,Santoli: Markets are marinating in macro anxie...,14 Hours Ago,https://www.cnbc.com/2022/07/01/santoli-market...
19,Biden says U.S. will protect women seeking abo...,14 Hours Ago,https://www.cnbc.com/2022/07/01/biden-to-meet-...
20,WHO says monkeypox cases triple in Europe in t...,14 Hours Ago,https://www.cnbc.com/2022/07/01/who-says-monke...
21,Stocks making the biggest moves midday: Micron...,15 Hours Ago,https://www.cnbc.com/2022/07/01/stocks-making-...
22,Omicron-specific Covid vaccines could be here ...,15 Hours Ago,https://www.cnbc.com/2022/07/01/what-to-know-a...
23,Biden names Apple co-founder Steve Jobs as rec...,15 Hours Ago,https://www.cnbc.com/2022/07/01/steve-jobs-awa...
24,Kohl's says a real estate sale is on the table...,15 Hours Ago,https://www.cnbc.com/2022/07/01/kohls-real-est...
25,Crypto billionaire Sam Bankman-Fried says more...,15 Hours Ago,https://www.cnbc.com/2022/07/01/crypto-billion...
26,Supreme Court EPA ruling is big setback for cl...,15 Hours Ago,https://www.cnbc.com/2022/07/01/the-supreme-co...
27,How Uvalde and Buffalo spurred push for first ...,15 Hours Ago,https://www.cnbc.com/2022/07/01/how-uvalde-and...
28,2022 is testing active equity ETFs. Find out i...,15 Hours Ago,https://www.cnbc.com/2022/07/01/2022-downturn-...
29,"There's a massive pile-up of car, furniture ex...",15 Hours Ago,https://www.cnbc.com/2022/07/01/massive-pile-u...

In [7]:
#Question 8 most downloaded articles in last 90 days
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url='https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles'

def journal_webscraping(url):
    source=requests.get(url)
    soup=BeautifulSoup(source.text,"html.parser")
    
    title=[]
    paper_url=[]
    authors=[]
    publ_date=[]
    
    articles = soup.find('ul',class_="sc-9zxyh7-0 ffmPq").find_all('li',class_="sc-9zxyh7-1 sc-9zxyh7-2 exAXfr jQmQZp")
    
    for i in articles:
        title.append(i.find('h2').text)
        paper_url.append(i.find('a')['href'])
        authors.append(i.find('span',class_='sc-1w3fpd7-0 pgLAT').text.split(','))
        publ_date.append(i.find('span',class_='sc-1thf9ly-2 bKddwo').text)

    articles_df=pd.DataFrame({'Title':title,'Authors':authors,'Published URL':paper_url,'Published Date':publ_date})
    return articles_df

journal_webscraping(url)

,Title,Authors,Published URL,Published Date
0,Reward is enough,"[Silver, David, Singh, Satinder, Precup, ...",https://www.sciencedirect.com/science/article/...,October 2021
1,Making sense of raw input,"[Evans, Richard, Bošnjak, Matko and 5 more]",https://www.sciencedirect.com/science/article/...,October 2021
2,Law and logic: A review from an argumentation ...,"[Prakken, Henry, Sartor, Giovanni ]",https://www.sciencedirect.com/science/article/...,October 2015
3,Creativity and artificial intelligence,"[Boden, Margaret A. ]",https://www.sciencedirect.com/science/article/...,August 1998
4,Artificial cognition for social human–robot in...,"[Lemaignan, Séverin, Warnier, Mathieu and 3...",https://www.sciencedirect.com/science/article/...,June 2017
5,Explanation in artificial intelligence: Insigh...,"[Miller, Tim ]",https://www.sciencedirect.com/science/article/...,February 2019
6,Making sense of sensory input,"[Evans, Richard, Hernández-Orallo, José and...",https://www.sciencedirect.com/science/article/...,April 2021
7,Conflict-based search for optimal multi-agent ...,"[Sharon, Guni, Stern, Roni, Felner, Ariel...",https://www.sciencedirect.com/science/article/...,February 2015
8,Between MDPs and semi-MDPs: A framework for te...,"[Sutton, Richard S., Precup, Doina, Singh,...",https://www.sciencedirect.com/science/article/...,August 1999
9,The Hanabi challenge: A new frontier for AI re...,"[Bard, Nolan, Foerster, Jakob N. and 13 more]",https://www.sciencedirect.com/science/article/...,March 2020
10,Evaluating XAI: A comparison of rule-based and...,"[van der Waa, Jasper, Nieuwburg, Elisabeth,...",https://www.sciencedirect.com/science/article/...,February 2021
11,Argumentation in artificial intelligence,"[Bench-Capon, T.J.M., Dunne, Paul E. ]",https://www.sciencedirect.com/science/article/...,October 2007
12,Algorithms for computing strategies in two-pla...,"[Bošanský, Branislav, Lisý, Viliam and 3 more]",https://www.sciencedirect.com/science/article/...,August 2016
13,Multiple object tracking: A literature review,"[Luo, Wenhan, Xing, Junliang and 4 more]",https://www.sciencedirect.com/science/article/...,April 2021
14,Selection of relevant features and examples in...,"[Blum, Avrim L., Langley, Pat ]",https://www.sciencedirect.com/science/article/...,December 1997
15,A survey of inverse reinforcement learning: Ch...,"[Arora, Saurabh, Doshi, Prashant ]",https://www.sciencedirect.com/science/article/...,August 2021
16,Explaining individual predictions when feature...,"[Aas, Kjersti, Jullum, Martin, Løland, An...",https://www.sciencedirect.com/science/article/...,September 2021
17,A review of possible effects of cognitive bias...,"[Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz,...",https://www.sciencedirect.com/science/article/...,June 2021
18,Integrating social power into the decision-mak...,"[Pereira, Gonçalo, Prada, Rui, Santos, Pe...",https://www.sciencedirect.com/science/article/...,December 2016
19,“That's (not) the output I expected!” On the r...,"[Riveiro, Maria, Thill, Serge ]",https://www.sciencedirect.com/science/article/...,September 2021
20,Explaining black-box classifiers using post-ho...,"[Kenny, Eoin M., Ford, Courtney, Quinn, M...",https://www.sciencedirect.com/science/article/...,May 2021
21,Algorithm runtime prediction: Methods & evalua...,"[Hutter, Frank, Xu, Lin, Hoos, Holger H.,...",https://www.sciencedirect.com/science/article/...,January 2014
22,Wrappers for feature subset selection,"[Kohavi, Ron, John, George H. ]",https://www.sciencedirect.com/science/article/...,December 1997
23,Commonsense visual sensemaking for autonomous ...,"[Suchan, Jakob, Bhatt, Mehul, Varadarajan,...",https://www.sciencedirect.com/science/article/...,October 2021
24,"Quantum computation, quantum theory and AI","[Ying, Mingsheng ]",https://www.sciencedirect.com/science/article/...,February 2010

In [8]:
#Question 9 Scrape details from dineout
from bs4 import BeautifulSoup 
import requests
import pandas as pd
import numpy as np

url='https://www.dineout.co.in/delhi-restaurants/buffet-special'

def dineout_scraping(url):
       
    source=requests.get(url)
    data=BeautifulSoup(source.text,'html.parser')
    

    name=[]
    location=[]
    cuisine=[]
    rating=[]
    image_url=[]

    for i in data.find_all('div',class_='restnt-info cursor'):
        name.append(i.a.text)

    for i in data.find_all('div',class_='restnt-loc ellipsis'):
        location.append(i.text)

    for i in data.find_all('span',class_='double-line-ellipsis'):
        cuisine.append(i.text.split('|')[1])

    for i in data.find_all('div',class_='restnt-rating rating-4'):
        rating.append(i.text)

    for i in data.find_all('img',class_='no-img'):
        image_url.append(i['data-src'])
        
    dineout_df=pd.DataFrame({'Name Of Restaurant':name,'Cuisines Served':cuisine,'Locaiton':location,'Ratings':rating,'Image URL':image_url})
    return dineout_df
    

dineout_scraping(url)

,Name Of Restaurant,Cuisines Served,Locaiton,Ratings,Image URL
0,Castle Barbeque,"North Indian, Chinese","Connaught Place, Central Delhi",3.5,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,"North Indian, Asian, Italian","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,Castle Barbeque,"Chinese, North Indian","Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
3,Cafe Knosh,"Italian, Continental","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,"North Indian, Chinese","Gardens Galleria,Sector 38A, Noida",4,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,"North Indian, Italian","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,North Indian,"Taurus Sarovar Portico,Mahipalpur, South Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,North Indian,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.8,https://im1.dineout.co.in/images/uploads/resta...
8,World Cafe,"North Indian, Italian","Vibe by The Lalit Traveller,Sector 35, Faridabad",4.3,https://im1.dineout.co.in/images/uploads/resta...
9,Indian Grill Room,"North Indian, Mughlai","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...
10,Mad 4 Bar B Que,North Indian,"Sector 29, Faridabad",3.6,https://im1.dineout.co.in/images/uploads/resta...
11,Barbeque 29,"North Indian, Mughlai, Desserts, Beverages","NIT, Faridabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
12,Glasshouse,"European, Italian, Asian, Continental","DoubleTree By Hilton Gurugram Baani Square,Sec...",4,https://im1.dineout.co.in/images/uploads/resta...

In [9]:
#Question 10 scrape details from google scholar

from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

url='https://scholar.google.com/citations?view_op=top_venues&hl=en'

def google_webscraping(url):
    source=requests.get(url)
    soup=BeautifulSoup(source.text,"html.parser")
    
    publ_ds=soup.find('div',class_="gsc_mvt_table_wrapper").find('td')
    publ_ds
    
    rank=[]
    publication=[]
    h5_index=[]
    h5_mean=[]
    
    for i in soup.find_all('td',class_='gsc_mvt_p'):
        rank.append(i.text)
    
    for i in soup.find_all('td',class_='gsc_mvt_t'):
        publication.append(i.text)
        
    for i in soup.find_all('a',class_='gs_ibl gsc_mp_anchor'):
        h5_index.append(i.text)
        
    for i in soup.find_all('span',class_='gs_ibl gsc_mp_anchor'):
        h5_mean.append(i.text)
        
    rank = [int(s.replace('.','')) for s in rank]
    h5_index=[int(s) for s in h5_index]
    h5_mean=[int(s) for s in h5_mean] 
    
    google_publ_df=pd.DataFrame({'Rank':rank,'Publication':publication,'h5_index':h5_index,'h5_mean':h5_mean})
    return google_publ_df 

google_webscraping(url)

    Rank                                        Publication  h5_index  h5_mean
0      1                                             Nature       444      667
1      2                The New England Journal of Medicine       432      780
2      3                                            Science       401      614
3      4  IEEE/CVF Conference on Computer Vision and Pat...       389      627
4      5                                         The Lancet       354      635
..   ...                                                ...       ...      ...
95    96                       Journal of Business Research       145      233
96    97                                   Molecular Cancer       145      209
97    98                                            Sensors       145      201
98    99                              Nature Climate Change       144      228
99   100                    IEEE Internet of Things Journal       144      212

[100 rows x 4 columns]